services:
  app:
    build: ./backend
    container_name: frapes-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/frapes_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CASSANDRA_CONTACT_POINT=cassandra
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=frapes_analytics
    depends_on:
      mongo:
        condition: servicevx_started
      redis:
        condition: service_started
      cassandra:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M  # Limita el backend para dejar espacio a la BD

  frontend:
    build: ./frontend
    container_name: frapes-front
    restart: always
    ports:
      - "5173:5173"
    environment:
      # OJO: Aquí deberás poner la IP Pública de tu VM en producción
      # Ejemplo: VITE_API_URL=http://34.12.14.55:3001/api
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 512M

  mongo:
    image: mongo:latest
    container_name: frapes-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M # Mongo es eficiente, con 512MB aguanta proyectos escolares
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: frapes-redis
    restart: always
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 256M # Redis gasta muy poca RAM
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:latest
    container_name: frapes-cassandra
    restart: always
    ports:
      - "9042:9042" # Puerto nativo
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=FrapesCluster
      # --- CONFIGURACIÓN CRÍTICA PARA VM PEQUEÑA ---
      # Limita la memoria Java a 512MB. Sin esto, la VM explota.
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    deploy:
      resources:
        limits:
          memory: 1G # Le damos hasta 1GB al contenedor (512MB Heap + Overhead del OS)
          cpus: '1.5'
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT cluster_name FROM system.local'"]
      interval: 30s # Aumenté el intervalo porque Java tarda en arrancar
      timeout: 20s
      retries: 10
      start_period: 60s

volumes:
  mongo-data: