services:
  app:
    build: ./backend
    container_name: frapes-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/frapes_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CASSANDRA_CONTACT_POINT=cassandra
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=frapes_analytics
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
      cassandra:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frapes-front
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app            # Espejo: Lo que editas en Windows se ve en Docker
      - /app/node_modules       # Truco: Evita que tu node_modules local vac√≠o borre el del contenedor
    environment:
      # Vite requiere esto para trabajar bien dentro de Docker
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app

  mongo:
    image: mongo:latest
    container_name: frapes-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: frapes-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:latest
    container_name: frapes-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=FrapesCluster
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT cluster_name FROM system.local'"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

volumes:
  mongo-data: